FROM java:latest

RUN apt-get update -y

EXPOSE 8080

WORKDIR app

# zip generated by running 'activator dist'
COPY target/universal/play-scala-1.0-SNAPSHOT.zip app.zip
RUN unzip app.zip

WORKDIR play-scala-1.0-SNAPSHOT

ENTRYPOINT ["./bin/play-scala"]
CMD ["-Dhttp.port=8080"]
